autoInstallPeers: false
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': set this to true or false
  '@google/genai': set this to true or false
  koffi: set this to true or false
  node-pty: set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis-plugin-include@1.0.6'
  - '@deepseek-ai/cordis-plugin-loader@1.0.2'
  - '@deepseek-ai/cordis@4.0.1'
  - '@deepseek-ai/cosmokit@1.8.2'
